### ISSUE TITLE
Support for water cauldrons and tripwire hooks?

### ISSUE THREAD

**Issue by muzikbike** [Benonardo/MoreTranslucency#2]
This might be out of scope for this mod specifically, since it only intends to change glass, but it could be suitable for a sister mod since I suspect it's a very similar fix.

A major annoyance in modern versions is that water itself renders translucently as one would expect. However, cauldrons in the world ignore this fact, and render the water as completely opaque:
![2022-09-03_23 29 04](https://user-images.githubusercontent.com/52297970/188289551-b5ee8678-63f0-4604-93d7-b67452253959.png)

A much subtler issue arises with tripwire hooks. Tripwire itself is very slightly translucent. When connected to a valid tripwire circuit, the tripwire hook block model incorporates a length of the tripwire into itself as to appear connected. However, while the tripwire block itself supports translucency, the tripwire hook block does not, and as such tripwire in the tripwire hook's block space is completely opaque:
![2022-09-03_23 30 03](https://user-images.githubusercontent.com/52297970/188289569-11bb24f6-a25b-46d0-94fd-a1fb3110eefc.png)
![2022-09-03_23 30 14](https://user-images.githubusercontent.com/52297970/188289570-d6b11cc1-fdaf-47a1-baca-b13711316c22.png)

The fix here seems simple enough - just make the blocks minecraft:water_cauldron and minecraft:tripwire_hook use transparent rendering, like how water and tripwire themselves do.

**Comment by Benonardo** [comment]
Sorry for the late response, will probably look into that tomorrow. Maybe I should rename the mod to MoreTranslucency or BetterTranslucency? Creating a separate one doesn't seem reasonable to me.

**Comment by muzikbike** [comment]
If you want to incorporate these fixes into this mod then I suppose that'd be fine, but personally I'd prefer a separate mod since fixing these two blocks has an apparent improvement even without a resource pack, whereas making glass and related blocks translucent and not having a resource pack active that utilizes said change does nothing other than port over translucency-related rendering issues to the block. Your call, though.

**Comment by Benonardo** [comment]
Turns out the cauldron thing is a bit tricky, since Minecraft essentially just renders the raw water texture onto a flat model, so that isn't easy to fix without rewriting cauldron rendering, which I am not sure I am capable of. Anyways, if I can fix it, it will end up in a separate mod. But i think i will put the tripwire fix into this one, since that is essentially doing the same thing as with beacons and glass (just that it has a direct effect in the game, if I understood you correctly). Closing this now, will rename the mod and put tripwires in.
